Version 4
SymbolType CELL
LINE Normal -61 -32 -48 -16
LINE Normal -35 -32 -61 -32
LINE Normal -48 -16 -35 -32
LINE Normal -35 -16 -61 -16
LINE Normal -48 -32 -48 -48
LINE Normal -80 -48 -48 -48
LINE Normal -48 0 -48 -16
LINE Normal -80 0 -48 0
LINE Normal 25 -48 25 -32
LINE Normal 80 -48 25 -48
LINE Normal 25 48 25 -16
LINE Normal 80 48 25 48
LINE Normal 28 -32 37 -16
LINE Normal 45 -32 28 -32
LINE Normal 37 -16 45 -32
LINE Normal 48 -16 20 -16
LINE Normal 20 -16 11 -32
LINE Normal 2 -16 20 -16
LINE Normal 11 -32 2 -16
LINE Normal -1 -32 28 -32
LINE Normal -9 -32 -27 -32
LINE Normal -15 -36 -9 -32
LINE Normal -14 -28 -9 -32
LINE Normal -9 -16 -27 -16
LINE Normal -15 -20 -9 -16
LINE Normal -14 -12 -9 -16
LINE Normal 48 -32 45 -32
LINE Normal -1 -16 2 -16
RECTANGLE Normal 80 80 -81 -80
TEXT -73 -59 Left 2 led+
TEXT -73 10 Left 2 led-
TEXT 38 -58 Left 2 mt2
TEXT 40 38 Left 2 mt1
TEXT -75 47 Left 2 nc
TEXT -88 48 Right 2 3
TEXT 49 -2 Left 2 nc!
TEXT 89 0 Left 2 5
WINDOW 38 0 70 Center 2
WINDOW 0 0 -71 Center 2
SYMATTR SpiceModel MOC3022
SYMATTR ModelFile ..\sym\_PERSONAL\opto\MOC302x.sub
SYMATTR Value MOC3022
SYMATTR Value2 MOC3022
SYMATTR Prefix X
SYMATTR Description NON zero crossing OPTO-TRIAC trigger current 10mA, holding current 100uA
PIN -80 -48 RIGHT 8
PINATTR PinName 1
PINATTR SpiceOrder 1
PIN -80 0 RIGHT 8
PINATTR PinName 2
PINATTR SpiceOrder 2
PIN 80 -48 LEFT 8
PINATTR PinName 6
PINATTR SpiceOrder 3
PIN 80 48 LEFT 8
PINATTR PinName 4
PINATTR SpiceOrder 4
