Version 4
SymbolType CELL
LINE Normal -61 -32 -48 -16
LINE Normal -35 -32 -61 -32
LINE Normal -48 -16 -35 -32
LINE Normal -35 -16 -61 -16
LINE Normal -48 -32 -48 -48
LINE Normal -80 -48 -48 -48
LINE Normal -48 0 -48 -16
LINE Normal -80 0 -48 0
LINE Normal 25 -48 25 -32
LINE Normal 80 -48 25 -48
LINE Normal 25 48 25 -16
LINE Normal 80 48 25 48
LINE Normal 21 -32 12 -16
LINE Normal 4 -32 21 -32
LINE Normal 12 -16 4 -32
LINE Normal 1 -16 29 -16
LINE Normal 29 -16 38 -32
LINE Normal 47 -16 29 -16
LINE Normal 38 -32 47 -16
LINE Normal 50 -32 21 -32
LINE Normal -9 -32 -27 -32
LINE Normal -15 -36 -9 -32
LINE Normal -14 -28 -9 -32
LINE Normal -9 -16 -27 -16
LINE Normal -15 -20 -9 -16
LINE Normal -14 -12 -9 -16
LINE Normal 1 -32 4 -32
LINE Normal 50 -16 47 -16
LINE Normal -6 -48 25 -48
LINE Normal -6 3 -6 -48
LINE Normal 19 3 -6 3
LINE Normal 19 36 19 3
LINE Normal -25 36 19 36
LINE Normal -25 3 -25 36
LINE Normal -6 3 -25 3
LINE Normal 2 -10 2 3
LINE Normal 12 -16 2 -10
LINE Normal 25 20 19 20
RECTANGLE Normal 80 80 -81 -80
TEXT -73 -59 Left 2 led+
TEXT -73 10 Left 2 led-
TEXT 38 -58 Left 2 mt2
TEXT 40 38 Left 2 mt1
TEXT -75 47 Left 2 nc
TEXT -88 48 Right 2 3
TEXT 49 -2 Left 2 nc!
TEXT 89 0 Left 2 5
TEXT -2 9 Center 2 zero
TEXT -4 25 Center 2 ckt
WINDOW 38 0 70 Center 2
WINDOW 0 0 -71 Center 2
SYMATTR ModelFile ..\sym\_PERSONAL\opto\MOC308x.sub
SYMATTR SpiceModel MOC3083
SYMATTR Value MOC3083
SYMATTR Value2 MOC3083
SYMATTR Prefix X
SYMATTR Description ZERO crossing OPTO-TRIAC trigger current 5mA, holding current 100uA
PIN -80 -48 RIGHT 8
PINATTR PinName 1
PINATTR SpiceOrder 1
PIN -80 0 RIGHT 8
PINATTR PinName 2
PINATTR SpiceOrder 2
PIN 80 -48 LEFT 8
PINATTR PinName 6
PINATTR SpiceOrder 3
PIN 80 48 LEFT 8
PINATTR PinName 4
PINATTR SpiceOrder 4
