Version 4
SymbolType CELL
LINE Normal -61 -32 -48 -16
LINE Normal -35 -32 -61 -32
LINE Normal -48 -16 -35 -32
LINE Normal -35 -16 -61 -16
LINE Normal -48 -32 -48 -48
LINE Normal -96 -48 -48 -48
LINE Normal -48 0 -48 -16
LINE Normal -96 0 -48 0
LINE Normal 25 -48 25 -32
LINE Normal 96 -48 25 -48
LINE Normal 25 48 25 -16
LINE Normal 96 48 25 48
LINE Normal 28 -32 37 -16
LINE Normal 45 -32 28 -32
LINE Normal 37 -16 45 -32
LINE Normal 48 -16 20 -16
LINE Normal 20 -16 11 -32
LINE Normal 2 -16 20 -16
LINE Normal 11 -32 2 -16
LINE Normal -1 -32 28 -32
LINE Normal -9 -32 -27 -32
LINE Normal -15 -36 -9 -32
LINE Normal -14 -28 -9 -32
LINE Normal -9 -16 -27 -16
LINE Normal -15 -20 -9 -16
LINE Normal -14 -12 -9 -16
LINE Normal 48 -32 45 -32
LINE Normal -1 -16 2 -16
RECTANGLE Normal 96 80 -96 -80
TEXT -79 -60 Left 2 led+
TEXT -79 11 Left 2 led-
TEXT 42 -60 Left 2 mt2
TEXT 42 36 Left 2 mt1
TEXT -83 46 Left 2 nc3
TEXT -112 48 Center 2 3
TEXT 47 -2 Left 2 nc5
TEXT 112 0 Center 2 5
WINDOW 38 3 65 Center 2
WINDOW 0 7 -66 Center 2
SYMATTR SpiceModel MOC3023
SYMATTR ModelFile ..\sym\_PERSONAL\opto\MOC302x.sub
SYMATTR Value MOC3023
SYMATTR Value2 MOC3023
SYMATTR Prefix X
SYMATTR Description NON zero crossing OPTO-TRIAC trigger current 5mA, holding current 100uA
PIN -96 -48 RIGHT 8
PINATTR PinName 1
PINATTR SpiceOrder 1
PIN -96 0 RIGHT 8
PINATTR PinName 2
PINATTR SpiceOrder 2
PIN 96 -48 LEFT 8
PINATTR PinName 6
PINATTR SpiceOrder 3
PIN 96 48 LEFT 8
PINATTR PinName 4
PINATTR SpiceOrder 4
